---
title: "liz.rmd"
output:
  html_document: default
  pdf_document: default
date: "2023-04-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("ggplot2")
library("usmap")
```

```{r, echo = FALSE}
pop <- read.csv("../../census_pop.csv") 


lawyers_per1k <- round((pop$lawyers_2021 / pop$pop_2021 * 1000), 2)
states <- state.name[match(pop$state, state.abb)]


lawyers <- data.frame(tolower(states), lawyers_per1k)
lawyers <- lawyers[-9,] %>%
  rename(state = tolower.states.)

lstate_shape <- map_data("state") %>%
  rename(state = region) %>%
  left_join(lawyers, by="state")

#View(lstate_shape)


all_q <- read.csv("../../questionpostsprocessed.csv") %>% 
  count(StateAbbr)


q_bystate <- all_q[-c(1:13, 46), ] %>%
  rename(num_q = n,
         state = StateAbbr)

merged <- merge(pop, q_bystate, by="state") 

join_qpop <- merged[, -c(2,3,5)] %>%
  mutate(q_per1k = round((num_q / pop_2021 * 1000), 2),
         lawyer_per1k = round((lawyers_2021 / pop_2021 * 1000), 2))

#join_qpop <- rename(join_qpop, abbr = state)

#View(join_qpop)
state <- state.name[match(join_qpop$abbr, state.abb)]

data <- mutate(join_qpop, state = tolower(state))
#View(data)

questions <- select(data, q_per1k, state)
#view(questions)



qstate_shape <- map_data("state") %>%
  rename(state = region) %>%
  left_join(questions, by="state")
```

```{r}  
#------Questions-------
  ggplot(qstate_shape) +
    geom_polygon(
      mapping = aes(x = long, y = lat, group = group, fill = q_per1k),
      color = "#011D2A",
      size = .08
    ) +
    coord_map() +
    scale_fill_continuous(low = "#E3F6FF", high = "#055377", na.value = "#A3A3A3") +
    labs(fill = "Questions per 1000 People", title="Rate of Questions Posted") +
     theme(
        axis.text.x=element_blank(), 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x=element_blank(), 
        axis.text.y=element_blank(),  
        axis.ticks.y=element_blank()  
        )

#------Lawyers-----------
```



```{r}

lstate_shape <- map_data("state") %>%
  rename(state = region) %>%
  left_join(lawyers, by="state")

 ggplot(lstate_shape) +
    geom_polygon(
      mapping = aes(x = long, y = lat, group = group, fill = lawyers_per1k),
      color = "#010923",
      size = .08
    ) +
    coord_map() +
    scale_fill_continuous(low = "white", high = "steelblue", na.value = "#A3A3A3") +
    labs(fill = "Lawyers per 1000 people", title="Active Lawyers per State") +
     theme(
        axis.text.x=element_blank(), 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x=element_blank(), 
        axis.text.y=element_blank(),  
        axis.ticks.y=element_blank()  
        )
 
 ```
 
 ```{r echo=FALSE}
#------------wrangling hours------------
 
all_entries <- read.csv("../../attorneytimeentries.csv")
volunteers <- read.csv("../../attorneys.csv")
 
l_eastate <- volunteers %>%
  count(StateAbbr) %>%
  rename(num_volunteers = n,
         state = StateAbbr) 

#View(l_eastate)

state_hrs <- all_entries %>% 
  group_by(StateAbbr) %>%
  summarise(sum(Hours, na.rm = TRUE)) %>%
  rename(total = 2,) %>%
  slice(-33) %>%
  rename(state = StateAbbr)


matching <- filter(l_eastate, l_eastate$state %in% state_hrs$state)


both <- left_join(matching, state_hrs, by="state") %>%
  rename(total_hrs = total)

statenames <- state.name[match(state_hrs$state, state.abb)]


hrs_perlawyer <- both %>% 
  mutate(
    state = tolower(statenames),
    hrs_perlawyer = round((total_hrs / num_volunteers), 2)
  ) 

# View(hrs_perlawyer)
```



```{r}
hrsstate_shape <- map_data("state") %>%
  rename(state = region) %>%
  left_join(hrs_perlawyer, by="state")

 ggplot(hrsstate_shape) +
    geom_polygon(
      mapping = aes(x = long, y = lat, group = group, fill = log(1 + hrs_perlawyer)),
      color = "#010923",
      size = .08
    ) +
    coord_map() +
    scale_fill_continuous(low = "white", high = "steelblue", na.value = "#A3A3A3") +
    labs(fill = "Hours per Lawyer (in log scale)", title="Hours Answered per Volunteer") +
     theme(
        axis.text.x=element_blank(), 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x=element_blank(), 
        axis.text.y=element_blank(),  
        axis.ticks.y=element_blank()  
        )




```




