---
title: "test"
output: html_document
date: "2023-04-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r date functions and constants}
time_limit <- as.POSIXct("2016-08-05", format = "%Y-%m-%d", tz = "UTC")

get_time <- function(time) {
  return(as.POSIXct(time, format = "%Y-%m-%d %H:%M:%OS", tz = "UTC"))
}
```

```{r Filter the data}
questionpostsprocessed <- read.csv("../../questionpostsprocessed.csv")
```

```{r}
questions <- read.csv("../../questions.csv") %>% 
  filter(get_time(AskedOnUtc) > time_limit) %>%
  arrange(CategoryUno, QuestionUno) %>% 
  select(-c(CategoryUno, SubcategoryUno))
```

Identifying trends of questions being asked across time (from 2016-2022)

```{r}
questions %>%
  mutate(
    AskedOnYear = year(get_time(AskedOnUtc)),
    AskedOnMonth = (year(get_time(AskedOnUtc)) - 2016) * 12 + month(get_time(AskedOnUtc))
  ) %>%
  group_by(AskedOnMonth, Category) %>%
  summarize(
    n = n()
  ) %>%
  ggplot(mapping = aes(x = AskedOnMonth, y = n, color = Category)) +
  geom_line()
```


```{r}
merged_questionposts <- merge(questionpostsprocessed, questions, by = "QuestionUno") %>%
  select(Category, PostTextProcessed) %>%
  write.csv(path = "/Users/wjtan/Downloads/DataFest 2023 Data For Distribution/datamerged.csv")

```
